# Generated by Django 5.2.3 on 2026-01-31 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0032_registrationapplication_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subreviewerinvite',
            name='invitee_name',
            field=models.CharField(blank=True, help_text='Name of the invitee (for non-registered users)', max_length=255),
        ),
        migrations.AlterField(
            model_name='subreviewerinvite',
            name='subreviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subreviewer_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['conference', 'author', 'status'], name='conference__confere_aa2168_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['conference', 'submitted_at'], name='conference__confere_3f85c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='paper',
            constraint=models.UniqueConstraint(fields=('title', 'author', 'conference'), name='unique_paper_per_author_conference'),
        ),
    ]
