# Generated by Django 5.2.3 on 2026-02-17 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0033_add_invitee_name_and_make_subreviewer_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="paper_id",
            field=models.CharField(
                blank=True,
                help_text="Unique Paper ID for search/reference",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="paper",
            constraint=models.UniqueConstraint(
                fields=("conference", "paper_id"), name="unique_paper_id_per_conference"
            ),
        ),
    ]
