# Generated by Django 5.2.3 on 2026-03-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0034_alter_paper_paper_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("desk_reject", "Desk Reject"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
